name: Build & Push nextjs to azure container
on:
  push:
    branch: main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with: 
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_ENDPOINT }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with: 
          push: true
          tags: ${{ secrets.ACR_ENDPOINTS }}/brandhub:latest
          file: ./Dockerfile
